version: "3"
services:
  # Service Name Defined as web
  web:
    # Pull the Image from Repository.
    # replace username/repo:tag with your name and image details
    image: yshailesh25/friendly_hello:latest 
    # Command used to deploy the Service
    deploy:
      # Run 5 instances of that image as a service called web
      replicas: 5
      resources:   #how many resourse this service can use > to check bottle neck or load
        # Limiting each one to use, at most, 10% of a single core of CPU time and 50MB of RAM.
        limits:
          cpus: "0.1"
          memory: 50M
      # Immediately restart containers if one fails.     
      restart_policy:
        condition: on-failure
    # Map port 4000 on the host to web’s port 80.    
    ports:
      - "4000:80"
    # Define default network  
    networks:
      - webnet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet  
      
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:   #this is persistent data problem to overcome this change (cont below)
      - "./data:/data" #  "/home/docker/data" to "./data" in your local so you want face persData issue
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes #prepare appendonly.aof file which save number of visits on site
    networks:
      - webnet    
networks:
  webnet: